#include <stdio.h>
#include <gctypes.h>
#include "getFgColorPattern.h"
#include "setFontFgColor.h"
//version finale
extern enum CONSOLE_FONT_WEIGHTS CURRENT_FONT_WEIGHT;
extern enum CONSOLE_FONT_WEIGHTS PREVIOUS_FONT_WEIGHT;
extern enum CONSOLE_FONT_COLORS PREVIOUS_FONT_FGCOLOR;
extern enum CONSOLE_FONT_COLORS CURRENT_FONT_FGCOLOR;
void setFontFgColor(enum CONSOLE_FONT_COLORS FONT_COLOR,enum CONSOLE_FONT_WEIGHTS FONT_WEIGHT) {
    if (FONT_COLOR==CONSOLE_FONT_CURRENT_COLOR) {
        FONT_COLOR=CURRENT_FONT_FGCOLOR;
    }
    if (CONSOLE_FONT_CURRENT_WEIGHT==FONT_WEIGHT) {
        FONT_WEIGHT=CURRENT_FONT_WEIGHT;
    }
    PREVIOUS_FONT_FGCOLOR=CURRENT_FONT_FGCOLOR;
    PREVIOUS_FONT_WEIGHT=CURRENT_FONT_WEIGHT;
    printf(getFgColorPattern(FONT_COLOR,FONT_WEIGHT));
    CURRENT_FONT_FGCOLOR=FONT_COLOR;
    CURRENT_FONT_WEIGHT=FONT_WEIGHT;
}
