#ifndef _SETFONTSTYLE_H_
#define _SETFONTSTYLE_H_
#include "video.h"
void setFontStyle(enum CONSOLE_FONT_COLORS FONT_BGCOLOR,enum CONSOLE_FONT_COLORS FONT_FGCOLOR,enum CONSOLE_FONT_WEIGHTS FONT_WEIGHT);
#endif
