#include "../../main.h"
#include "video.h"
enum CONSOLE_FONT_COLORS CURRENT_FONT_BGCOLOR=DEFAULT_FONT_BGCOLOR,PREVIOUS_FONT_BGCOLOR=DEFAULT_FONT_BGCOLOR,CURRENT_FONT_FGCOLOR=DEFAULT_FONT_FGCOLOR,PREVIOUS_FONT_FGCOLOR=DEFAULT_FONT_FGCOLOR;
enum CONSOLE_FONT_WEIGHTS PREVIOUS_FONT_WEIGHT=DEFAULT_FONT_WEIGHT,CURRENT_FONT_WEIGHT=DEFAULT_FONT_WEIGHT;
unsigned char CONSOLE_CURSOR_CURRENT_COLUMN=0,CONSOLE_CURSOR_PREVIOUS_COLUMN=0,CONSOLE_CURSOR_CURRENT_ROW=0,CONSOLE_CURSOR_PREVIOUS_ROW=0;
