#ifndef _SYSTEM_H_
#define _SYSTEM_H_
#include <gctypes.h>
#define	HW_PPCSPEED	((vu32 *)0xCD800018)
#define SOFT_RESET ((vu32 *)0xCC003024)
#define APPLOADER_LOADING_ADDRESS (void *) 0x81200000
#define THERMAL_INTERRUPT (void *) 0x80001700
#define TV_MODE ((vu32 *)0x800000CC)
enum SRAM_GC_LANGUAGES {
    SRAM_GC_ENGLISH_LANGUAGE=0,
    SRAM_GC_GERMAN_LANGUAGE=1,
    SRAM_GC_FRENCH_LANGUAGE=2,
    SRAM_GC_SPANISH_LANGUAGE=3,
    SRAM_GC_ITALIAN_LANGUAGE=4,
    SRAM_GC_DUTCH_LANGUAGE=5,
    SRAM_GC_CONSOLE_LANGUAGE=6
};
enum {
    IOCTL_BUFFER_SIZE=32
};
#endif
