#ifndef _MIOS_H_
#define _MIOS_H_
#include <gctypes.h>
#include "../video/video.h"
#define MIOS_INFOS_FAMILY_ID_LABEL "FAMILY ID"
#define MIOS_INFOS_DEVICES_LABEL "DEVICES"
#define MIOS_INFOS_PRIORITY_TITLES_LABEL "PRIORITY TITLES"
#define MIOS_INFOS_UNSUPPORTED_TITLES_LABEL "UNSUPPORTED TITLES"
#define MIOS_INFOS_DEDICATED_TITLES_LABEL "DEDICATED TITLES"
#define DIOS_MIOS_FAMILY_ID "dm"
#define DIOS_MIOS_MAGICWORD 0xD1050CF6
#define MIOS_HOMEBREW_ADDRESS (void *) 0x80800000
#define MIOS_MAGICWORD_ADDRESS (char *) 0x807FFFE0
enum MIOS_WAD_INSTALLATION_STATUS {
    MIOS_WAD_INSTALLATION_ERROR=CONSOLE_FONT_RED,
    MIOS_WAD_INSTALLATION_BAD_TITLE=CONSOLE_FONT_BLACK,
    MIOS_WAD_INSTALLATION_OK=CONSOLE_FONT_GREEN,
    MIOS_WAD_INSTALLATION_UNKNOWN_MIOS=CONSOLE_FONT_MAGENTA,
    MIOS_WAD_INSTALLATION_ALREADY_INSTALLED=CONSOLE_FONT_BLUE
};
struct stDiosMiosSettings {
	u32 intMagicbytes;
	u32 intCfgVersion;
	u32 intVideoMode;
	u32 intOptions;
	char strGamePath[256];
	char strCheatsPath[256];
};
enum {
    DIOS_MIOS_SETTINGS_STRUCTURE_SIZE=sizeof(struct stDiosMiosSettings)
};
enum DIOS_MIOS_OPTIONS {
	DIOS_MIOS_CHEATS=(1<<0),
	DIOS_MIOS_DEBUGGER=(1<<1),
	DIOS_MIOS_DEBUG_WAIT=(1<<2),
	DIOS_MIOS_NMM=(1<<3),
	DIOS_MIOS_NMM_DEBUG=(1<<4),
	DIOS_MIOS_GAME_PATH=(1<<5),
	DIOS_MIOS_CHEATS_PATH=(1<<6),
	DIOS_MIOS_LED=(1<<7),
	DIOS_MIOS_PADHOOK=(1<<8),
	DIOS_MIOS_WIDESCREEN=(1<<9),
	DIOS_MIOS_BOOT_DISC=(1<<10),
	DIOS_MIOS_BOOT_DISC2=(1<<11),
	DIOS_MIOS_NODISC=(1<<12)
};
enum DIOS_MIOS_VIDEO_MODES {
	DIOS_MIOS_VIDEO_AUTO=(0<<16),
	DIOS_MIOS_VIDEO_FORCE=(1<<16),
	DIOS_MIOS_VIDEO_NONE=(2<<16),
	DIOS_MIOS_VIDEO_FORCE_PAL50=(1<<0),
	DIOS_MIOS_VIDEO_FORCE_PAL60=(1<<1),
	DIOS_MIOS_VIDEO_FORCE_NTSC=(1<<2),
	DIOS_MIOS_VIDEO_FORCE_PROGRESSIVE=(1<<3),
	DIOS_MIOS_VIDEO_PROGRESSIVE_PATCH=(1<<4)
};
#endif
